# Generated by Django 2.2.5 on 2019-09-28 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rutas',
            fields=[
                ('idRuta', models.AutoField(primary_key=True, serialize=False)),
                ('estacionInicio', models.IntegerField(default=0)),
                ('estacionDestino', models.IntegerField(default=0)),
                ('rutaNodos', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='rutasProcesar',
            fields=[
                ('idProcesar', models.AutoField(primary_key=True, serialize=False)),
                ('estacionInicioP', models.IntegerField(default=0)),
                ('estacionDestinoP', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='tablaSuma',
            fields=[
                ('idOperacion', models.AutoField(primary_key=True, serialize=False)),
                ('dato1', models.IntegerField(default=0)),
                ('dato2', models.IntegerField(default=0)),
                ('resultado', models.IntegerField(default=0)),
            ],
        ),
    ]
