# Generated by Django 2.2.5 on 2019-09-28 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapa_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Puntos',
            new_name='puntoMapa',
        ),
    ]
